// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/KVs.proto

package org.inlighting.sfm.proto;

public final class KVsProtos {
  private KVsProtos() {}
  public static void registerAllExtensions(
      org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.apache.hadoop.thirdparty.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hadoop.hdfs.sfm.KV)
      org.apache.hadoop.thirdparty.protobuf.MessageOrBuilder {

    /**
     * <code>required string filename = 1;</code>
     */
    boolean hasFilename();
    /**
     * <code>required string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>required string filename = 1;</code>
     */
    org.apache.hadoop.thirdparty.protobuf.ByteString
        getFilenameBytes();

    /**
     * <pre>
     * offset should be long
     * </pre>
     *
     * <code>optional uint64 offset = 2;</code>
     */
    boolean hasOffset();
    /**
     * <pre>
     * offset should be long
     * </pre>
     *
     * <code>optional uint64 offset = 2;</code>
     */
    long getOffset();

    /**
     * <code>optional uint32 length = 3;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint32 length = 3;</code>
     */
    int getLength();

    /**
     * <code>required bool tombstone = 4;</code>
     */
    boolean hasTombstone();
    /**
     * <code>required bool tombstone = 4;</code>
     */
    boolean getTombstone();
  }
  /**
   * Protobuf type {@code hadoop.hdfs.sfm.KV}
   */
  public  static final class KV extends
      org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hadoop.hdfs.sfm.KV)
      KVOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KV.newBuilder() to construct.
    private KV(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KV() {
      filename_ = "";
    }

    @java.lang.Override
    public final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KV(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet.Builder unknownFields =
          org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.apache.hadoop.thirdparty.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              filename_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offset_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              length_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              tombstone_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KVsProtos.internal_static_hadoop_hdfs_sfm_KV_descriptor;
    }

    @java.lang.Override
    protected org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KVsProtos.internal_static_hadoop_hdfs_sfm_KV_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KVsProtos.KV.class, KVsProtos.KV.Builder.class);
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <code>required string filename = 1;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        org.apache.hadoop.thirdparty.protobuf.ByteString bs = 
            (org.apache.hadoop.thirdparty.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filename = 1;</code>
     */
    public org.apache.hadoop.thirdparty.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        org.apache.hadoop.thirdparty.protobuf.ByteString b = 
            org.apache.hadoop.thirdparty.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (org.apache.hadoop.thirdparty.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 2;
    private long offset_;
    /**
     * <pre>
     * offset should be long
     * </pre>
     *
     * <code>optional uint64 offset = 2;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * offset should be long
     * </pre>
     *
     * <code>optional uint64 offset = 2;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private int length_;
    /**
     * <code>optional uint32 length = 3;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 length = 3;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int TOMBSTONE_FIELD_NUMBER = 4;
    private boolean tombstone_;
    /**
     * <code>required bool tombstone = 4;</code>
     */
    public boolean hasTombstone() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bool tombstone = 4;</code>
     */
    public boolean getTombstone() {
      return tombstone_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTombstone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(org.apache.hadoop.thirdparty.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, offset_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, length_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, tombstone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += org.apache.hadoop.thirdparty.protobuf.CodedOutputStream
          .computeUInt64Size(2, offset_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += org.apache.hadoop.thirdparty.protobuf.CodedOutputStream
          .computeUInt32Size(3, length_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += org.apache.hadoop.thirdparty.protobuf.CodedOutputStream
          .computeBoolSize(4, tombstone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof KVsProtos.KV)) {
        return super.equals(obj);
      }
      KVsProtos.KV other = (KVsProtos.KV) obj;

      if (hasFilename() != other.hasFilename()) return false;
      if (hasFilename()) {
        if (!getFilename()
            .equals(other.getFilename())) return false;
      }
      if (hasOffset() != other.hasOffset()) return false;
      if (hasOffset()) {
        if (getOffset()
            != other.getOffset()) return false;
      }
      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (getLength()
            != other.getLength()) return false;
      }
      if (hasTombstone() != other.hasTombstone()) return false;
      if (hasTombstone()) {
        if (getTombstone()
            != other.getTombstone()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilename()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + org.apache.hadoop.thirdparty.protobuf.Internal.hashLong(
            getOffset());
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength();
      }
      if (hasTombstone()) {
        hash = (37 * hash) + TOMBSTONE_FIELD_NUMBER;
        hash = (53 * hash) + org.apache.hadoop.thirdparty.protobuf.Internal.hashBoolean(
            getTombstone());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static KVsProtos.KV parseFrom(
        java.nio.ByteBuffer data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KV parseFrom(
        java.nio.ByteBuffer data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KV parseFrom(
        org.apache.hadoop.thirdparty.protobuf.ByteString data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KV parseFrom(
        org.apache.hadoop.thirdparty.protobuf.ByteString data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KV parseFrom(byte[] data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KV parseFrom(
        byte[] data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KV parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KVsProtos.KV parseFrom(
        java.io.InputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static KVsProtos.KV parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static KVsProtos.KV parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static KVsProtos.KV parseFrom(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KVsProtos.KV parseFrom(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(KVsProtos.KV prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hadoop.hdfs.sfm.KV}
     */
    public static final class Builder extends
        org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hadoop.hdfs.sfm.KV)
        KVsProtos.KVOrBuilder {
      public static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KV_descriptor;
      }

      @java.lang.Override
      protected org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KV_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KVsProtos.KV.class, KVsProtos.KV.Builder.class);
      }

      // Construct using org.inlighting.proto.KVsProtos.KV.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        tombstone_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KV_descriptor;
      }

      @java.lang.Override
      public KVsProtos.KV getDefaultInstanceForType() {
        return KVsProtos.KV.getDefaultInstance();
      }

      @java.lang.Override
      public KVsProtos.KV build() {
        KVsProtos.KV result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public KVsProtos.KV buildPartial() {
        KVsProtos.KV result = new KVsProtos.KV(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.offset_ = offset_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.length_ = length_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.tombstone_ = tombstone_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message other) {
        if (other instanceof KVsProtos.KV) {
          return mergeFrom((KVsProtos.KV)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KVsProtos.KV other) {
        if (other == KVsProtos.KV.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          bitField0_ |= 0x00000001;
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasTombstone()) {
          setTombstone(other.getTombstone());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFilename()) {
          return false;
        }
        if (!hasTombstone()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
          org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KVsProtos.KV parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KVsProtos.KV) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>required string filename = 1;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          org.apache.hadoop.thirdparty.protobuf.ByteString bs =
              (org.apache.hadoop.thirdparty.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public org.apache.hadoop.thirdparty.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          org.apache.hadoop.thirdparty.protobuf.ByteString b = 
              org.apache.hadoop.thirdparty.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (org.apache.hadoop.thirdparty.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>required string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          org.apache.hadoop.thirdparty.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <pre>
       * offset should be long
       * </pre>
       *
       * <code>optional uint64 offset = 2;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * offset should be long
       * </pre>
       *
       * <code>optional uint64 offset = 2;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * offset should be long
       * </pre>
       *
       * <code>optional uint64 offset = 2;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000002;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * offset should be long
       * </pre>
       *
       * <code>optional uint64 offset = 2;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>optional uint32 length = 3;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 length = 3;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>optional uint32 length = 3;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 length = 3;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0;
        onChanged();
        return this;
      }

      private boolean tombstone_ ;
      /**
       * <code>required bool tombstone = 4;</code>
       */
      public boolean hasTombstone() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required bool tombstone = 4;</code>
       */
      public boolean getTombstone() {
        return tombstone_;
      }
      /**
       * <code>required bool tombstone = 4;</code>
       */
      public Builder setTombstone(boolean value) {
        bitField0_ |= 0x00000008;
        tombstone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool tombstone = 4;</code>
       */
      public Builder clearTombstone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tombstone_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hadoop.hdfs.sfm.KV)
    }

    // @@protoc_insertion_point(class_scope:hadoop.hdfs.sfm.KV)
    private static final KVsProtos.KV DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KVsProtos.KV();
    }

    public static KVsProtos.KV getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final org.apache.hadoop.thirdparty.protobuf.Parser<KV>
        PARSER = new org.apache.hadoop.thirdparty.protobuf.AbstractParser<KV>() {
      @java.lang.Override
      public KV parsePartialFrom(
          org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
          org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
          throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
        return new KV(input, extensionRegistry);
      }
    };

    public static org.apache.hadoop.thirdparty.protobuf.Parser<KV> parser() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.hadoop.thirdparty.protobuf.Parser<KV> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public KVsProtos.KV getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KVsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hadoop.hdfs.sfm.KVs)
      org.apache.hadoop.thirdparty.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    java.util.List<KVsProtos.KV>
        getKvList();
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    KVsProtos.KV getKv(int index);
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    int getKvCount();
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    java.util.List<? extends KVsProtos.KVOrBuilder>
        getKvOrBuilderList();
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    KVsProtos.KVOrBuilder getKvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hadoop.hdfs.sfm.KVs}
   */
  public  static final class KVs extends
      org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hadoop.hdfs.sfm.KVs)
      KVsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVs.newBuilder() to construct.
    private KVs(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVs() {
      kv_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KVs(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet.Builder unknownFields =
          org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                kv_ = new java.util.ArrayList<KVsProtos.KV>();
                mutable_bitField0_ |= 0x00000001;
              }
              kv_.add(
                  input.readMessage(KVsProtos.KV.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          kv_ = java.util.Collections.unmodifiableList(kv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KVsProtos.internal_static_hadoop_hdfs_sfm_KVs_descriptor;
    }

    @java.lang.Override
    protected org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KVsProtos.internal_static_hadoop_hdfs_sfm_KVs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KVsProtos.KVs.class, KVsProtos.KVs.Builder.class);
    }

    public static final int KV_FIELD_NUMBER = 1;
    private java.util.List<KVsProtos.KV> kv_;
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    public java.util.List<KVsProtos.KV> getKvList() {
      return kv_;
    }
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    public java.util.List<? extends KVsProtos.KVOrBuilder>
        getKvOrBuilderList() {
      return kv_;
    }
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    public int getKvCount() {
      return kv_.size();
    }
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    public KVsProtos.KV getKv(int index) {
      return kv_.get(index);
    }
    /**
     * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
     */
    public KVsProtos.KVOrBuilder getKvOrBuilder(
        int index) {
      return kv_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getKvCount(); i++) {
        if (!getKv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(org.apache.hadoop.thirdparty.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < kv_.size(); i++) {
        output.writeMessage(1, kv_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < kv_.size(); i++) {
        size += org.apache.hadoop.thirdparty.protobuf.CodedOutputStream
          .computeMessageSize(1, kv_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof KVsProtos.KVs)) {
        return super.equals(obj);
      }
      KVsProtos.KVs other = (KVsProtos.KVs) obj;

      if (!getKvList()
          .equals(other.getKvList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getKvCount() > 0) {
        hash = (37 * hash) + KV_FIELD_NUMBER;
        hash = (53 * hash) + getKvList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static KVsProtos.KVs parseFrom(
        java.nio.ByteBuffer data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KVs parseFrom(
        java.nio.ByteBuffer data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KVs parseFrom(
        org.apache.hadoop.thirdparty.protobuf.ByteString data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KVs parseFrom(
        org.apache.hadoop.thirdparty.protobuf.ByteString data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KVs parseFrom(byte[] data)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KVsProtos.KVs parseFrom(
        byte[] data,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KVsProtos.KVs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KVsProtos.KVs parseFrom(
        java.io.InputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static KVsProtos.KVs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static KVsProtos.KVs parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static KVsProtos.KVs parseFrom(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KVsProtos.KVs parseFrom(
        org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
        org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(KVsProtos.KVs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hadoop.hdfs.sfm.KVs}
     */
    public static final class Builder extends
        org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hadoop.hdfs.sfm.KVs)
        KVsProtos.KVsOrBuilder {
      public static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KVs_descriptor;
      }

      @java.lang.Override
      protected org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KVs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KVsProtos.KVs.class, KVsProtos.KVs.Builder.class);
      }

      // Construct using org.inlighting.proto.KVsProtos.KVs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getKvFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (kvBuilder_ == null) {
          kv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          kvBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KVsProtos.internal_static_hadoop_hdfs_sfm_KVs_descriptor;
      }

      @java.lang.Override
      public KVsProtos.KVs getDefaultInstanceForType() {
        return KVsProtos.KVs.getDefaultInstance();
      }

      @java.lang.Override
      public KVsProtos.KVs build() {
        KVsProtos.KVs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public KVsProtos.KVs buildPartial() {
        KVsProtos.KVs result = new KVsProtos.KVs(this);
        int from_bitField0_ = bitField0_;
        if (kvBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            kv_ = java.util.Collections.unmodifiableList(kv_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.kv_ = kv_;
        } else {
          result.kv_ = kvBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message other) {
        if (other instanceof KVsProtos.KVs) {
          return mergeFrom((KVsProtos.KVs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KVsProtos.KVs other) {
        if (other == KVsProtos.KVs.getDefaultInstance()) return this;
        if (kvBuilder_ == null) {
          if (!other.kv_.isEmpty()) {
            if (kv_.isEmpty()) {
              kv_ = other.kv_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKvIsMutable();
              kv_.addAll(other.kv_);
            }
            onChanged();
          }
        } else {
          if (!other.kv_.isEmpty()) {
            if (kvBuilder_.isEmpty()) {
              kvBuilder_.dispose();
              kvBuilder_ = null;
              kv_ = other.kv_;
              bitField0_ = (bitField0_ & ~0x00000001);
              kvBuilder_ = 
                org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKvFieldBuilder() : null;
            } else {
              kvBuilder_.addAllMessages(other.kv_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getKvCount(); i++) {
          if (!getKv(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
          org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KVsProtos.KVs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KVsProtos.KVs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<KVsProtos.KV> kv_ =
        java.util.Collections.emptyList();
      private void ensureKvIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          kv_ = new java.util.ArrayList<KVsProtos.KV>(kv_);
          bitField0_ |= 0x00000001;
         }
      }

      private org.apache.hadoop.thirdparty.protobuf.RepeatedFieldBuilderV3<
          KVsProtos.KV, KVsProtos.KV.Builder, KVsProtos.KVOrBuilder> kvBuilder_;

      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public java.util.List<KVsProtos.KV> getKvList() {
        if (kvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kv_);
        } else {
          return kvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public int getKvCount() {
        if (kvBuilder_ == null) {
          return kv_.size();
        } else {
          return kvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public KVsProtos.KV getKv(int index) {
        if (kvBuilder_ == null) {
          return kv_.get(index);
        } else {
          return kvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder setKv(
          int index, KVsProtos.KV value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.set(index, value);
          onChanged();
        } else {
          kvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder setKv(
          int index, KVsProtos.KV.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder addKv(KVsProtos.KV value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.add(value);
          onChanged();
        } else {
          kvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder addKv(
          int index, KVsProtos.KV value) {
        if (kvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvIsMutable();
          kv_.add(index, value);
          onChanged();
        } else {
          kvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder addKv(
          KVsProtos.KV.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.add(builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder addKv(
          int index, KVsProtos.KV.Builder builderForValue) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder addAllKv(
          java.lang.Iterable<? extends KVsProtos.KV> values) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          org.apache.hadoop.thirdparty.protobuf.AbstractMessageLite.Builder.addAll(
              values, kv_);
          onChanged();
        } else {
          kvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder clearKv() {
        if (kvBuilder_ == null) {
          kv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          kvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public Builder removeKv(int index) {
        if (kvBuilder_ == null) {
          ensureKvIsMutable();
          kv_.remove(index);
          onChanged();
        } else {
          kvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public KVsProtos.KV.Builder getKvBuilder(
          int index) {
        return getKvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public KVsProtos.KVOrBuilder getKvOrBuilder(
          int index) {
        if (kvBuilder_ == null) {
          return kv_.get(index);  } else {
          return kvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public java.util.List<? extends KVsProtos.KVOrBuilder>
           getKvOrBuilderList() {
        if (kvBuilder_ != null) {
          return kvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kv_);
        }
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public KVsProtos.KV.Builder addKvBuilder() {
        return getKvFieldBuilder().addBuilder(
            KVsProtos.KV.getDefaultInstance());
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public KVsProtos.KV.Builder addKvBuilder(
          int index) {
        return getKvFieldBuilder().addBuilder(
            index, KVsProtos.KV.getDefaultInstance());
      }
      /**
       * <code>repeated .hadoop.hdfs.sfm.KV kv = 1;</code>
       */
      public java.util.List<KVsProtos.KV.Builder>
           getKvBuilderList() {
        return getKvFieldBuilder().getBuilderList();
      }
      private org.apache.hadoop.thirdparty.protobuf.RepeatedFieldBuilderV3<
          KVsProtos.KV, KVsProtos.KV.Builder, KVsProtos.KVOrBuilder>
          getKvFieldBuilder() {
        if (kvBuilder_ == null) {
          kvBuilder_ = new org.apache.hadoop.thirdparty.protobuf.RepeatedFieldBuilderV3<
              KVsProtos.KV, KVsProtos.KV.Builder, KVsProtos.KVOrBuilder>(
                  kv_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          kv_ = null;
        }
        return kvBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hadoop.hdfs.sfm.KVs)
    }

    // @@protoc_insertion_point(class_scope:hadoop.hdfs.sfm.KVs)
    private static final KVsProtos.KVs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KVsProtos.KVs();
    }

    public static KVsProtos.KVs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final org.apache.hadoop.thirdparty.protobuf.Parser<KVs>
        PARSER = new org.apache.hadoop.thirdparty.protobuf.AbstractParser<KVs>() {
      @java.lang.Override
      public KVs parsePartialFrom(
          org.apache.hadoop.thirdparty.protobuf.CodedInputStream input,
          org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite extensionRegistry)
          throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException {
        return new KVs(input, extensionRegistry);
      }
    };

    public static org.apache.hadoop.thirdparty.protobuf.Parser<KVs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.hadoop.thirdparty.protobuf.Parser<KVs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public KVsProtos.KVs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
    internal_static_hadoop_hdfs_sfm_KV_descriptor;
  private static final 
    org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hadoop_hdfs_sfm_KV_fieldAccessorTable;
  private static final org.apache.hadoop.thirdparty.protobuf.Descriptors.Descriptor
    internal_static_hadoop_hdfs_sfm_KVs_descriptor;
  private static final 
    org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hadoop_hdfs_sfm_KVs_fieldAccessorTable;

  public static org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031resources/proto/KVs.proto\022\017hadoop.hdfs" +
      ".sfm\"I\n\002KV\022\020\n\010filename\030\001 \002(\t\022\016\n\006offset\030\002" +
      " \001(\004\022\016\n\006length\030\003 \001(\r\022\021\n\ttombstone\030\004 \002(\010\"" +
      "&\n\003KVs\022\037\n\002kv\030\001 \003(\0132\023.hadoop.hdfs.sfm.KVB" +
      "$\n\024org.inlighting.protoB\tKVsProtos\240\001\001"
    };
    org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public org.apache.hadoop.thirdparty.protobuf.ExtensionRegistry assignDescriptors(
              org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.hadoop.thirdparty.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hadoop_hdfs_sfm_KV_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hadoop_hdfs_sfm_KV_fieldAccessorTable = new
      org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hadoop_hdfs_sfm_KV_descriptor,
        new java.lang.String[] { "Filename", "Offset", "Length", "Tombstone", });
    internal_static_hadoop_hdfs_sfm_KVs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hadoop_hdfs_sfm_KVs_fieldAccessorTable = new
      org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hadoop_hdfs_sfm_KVs_descriptor,
        new java.lang.String[] { "Kv", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
